### ISSUE TITLE
GPU/CUDA not being used

### ISSUE THREAD

**Issue by SteveH486** [C0untFloyd/roop-unleashed#1043]
Since ver 4.4.0, I'm pretty sure only CPU processing works, I see error:

2025-01-05 03:30:33.009942360 [E:onnxruntime:Default, provider_bridge_ort.cc:1862 TryGetProviderInfo_CUDA] /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1539 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_cuda.so with error: libcudnn_adv.so.9: cannot open shared object file: No such file or directory

Try to face swap any image video. On a 4090, get about 3 sec per frame. To prove not using GPU, I set processing to use CPU in roop-unleashed, same speed.
2025-01-05 03:30:33.009942360 [E:onnxruntime:Default, provider_bridge_ort.cc:1862 TryGetProviderInfo_CUDA] /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1539 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_cuda.so with error: libcudnn_adv.so.9: cannot open shared object file: No such file or directory

**Details**
What OS are you using?
- * Linux
- [ ] Linux in WSL
- [ ] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [*] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**
4.4.0, and tried 4.4.1

I tried to re--install onnxruntime, with:

pip uninstall onnxruntime-gpu
pip install onnxruntime-gpu==1.20.1

Did not enable CUDA GPU processing, same error.

Thanks for any help!

**Comment by C0untFloyd** [comment]
As stated multiple times you need to upgrade CUDA & CUDNN to at least v12.4:
https://developer.nvidia.com/cuda-downloads
https://developer.nvidia.com/rdp/cudnn-archive

**Comment by SteveH486** [comment]
Ah, OK thanks!

Was running on a runpod, maybe old install files, I just use:

```
!git clone https://github.com/C0untFloyd/roop-unleashed.git
%cd roop-unleashed
!mv config_colab.yaml config.yaml
!pip install -r requirements.txt
!python run.py
```

**Comment by SteveH486** [comment]
Yup, that fixed it, thanks!

If you have a donation page, I'm going to 'buy you a coffee' ;)
