### ISSUE TITLE
RuntimeError: onnxruntime::CudaCall CUBLAS failure 3: CUBLAS_STATUS_ALLOC_FAILED ; GPU=0; line=73 ; expr=cublasCreate(&cublas_handle_);

### ISSUE THREAD

**Issue by Vigneshkumar212** [C0untFloyd/roop-unleashed#1065]
Hey! ive used roop unleashed for a long time now and decided to install cuda and cudnn for another open souce project.
after installation i started getting this error.
This error shows up when i click on start.

Can you please let me know how to fix this.

Thanks!

**Comment by Vigneshkumar212** [comment]
Ohh here's the full error
RuntimeError: D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUBLAS failure 3: CUBLAS_STATUS_ALLOC_FAILED ; GPU=0 ; hostname=LAPTOP-LNF9BQ81 ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_stream_handle.cc ; line=73 ; expr=cublasCreate(&cublas_handle_);

**Comment by Vigneshkumar212** [comment]
Anyone facing a similar issue, I found a fix, it was an issue w cuda and cudnn version.
Find which version of the following package you have installed:
`onnx`
then google the supported cuda and cudnn version and install that version and it runs like butter

My rendering performance went from 7s/frame to 1s/frame on a gtx 1650 ti
