### ISSUE TITLE
Failed to allocate memory for requested buffer of size

### ISSUE THREAD

**Issue by Johannpcs** [C0untFloyd/roop-unleashed#425]
What OS are you using?
- [x] Windows 10

Are you using a GPU?
- [x] NVIDIA 1660 supper

16GB of 4000 MHz ram
I am on v3.5.0 of this program

For some reason, I started getting this error:
Error in execution: D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUBLAS failure 3: CUBLAS_STATUS_ALLOC_FAILED ; GPU=0 ;
file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_stream_handle.cc ; line=51 ; expr=cublasCreate(&cublas_handle_);

(Does this mean it's looking for it in my D hard drive (I don't have anything in my D drive) or is it just the naming since the program is running on my E drive (Nvme)).

and

onnxruntime::BFCArena::AllocateRawInternal Failed to allocate memory for requested buffer of size 67471254 (sometimes bigger sometimes smaller).

The weird thing is that it was working perfectly fine but then randomly stopped working, I didn't change any of the settings I even lowered most of them (after it stopped working) just the ones in the settings tab but now I can't run the same videos I already did (but the image face swap still works only the videos seem to be messed up) and on a side note is the long wait before generating an image usual since for me I usually have to wait 20/40 sec with no progress bar and then it just instantly finishes.

**Comment by Johannpcs** [comment]
Tried reinstalling but then it only worked with 2 threads while using even the bad post processing (weirdly it seems to be doing worse when I gave it 3 threads max) any more and it gave me the memory allocation error, while I was using it with 12 threads (ryzen 5 3600) and it worked and was way faster (talking about video face swaps).

**Comment by Johannpcs** [comment]
> Simple answer: your 1660 Super has only 6 Gb RAM and more than 2 threads are not possible with it. Actually I believe that for using post-processing you even have to set it to 1 thread. More isn't always better because every thread uses up your precious VRAM.
> 
> > while I was using it with 12 threads (ryzen 5 3600) and it worked and was way faster
> 
> Because your Ryzen wasn't even used and everything was running on the CPU (AMD is only supported if you're installing directml etc. which I doubt you've done). Anyway, a longer explanation about the threads can be found here: https://github.com/C0untFloyd/roop-unleashed/wiki/FAQ


Well is there a way to speed up the generation then?
Since now the same 5 second clips take up 15/17 min to generate when they only took 3/4 min (same video, same face).
