### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Ilay33** [C0untFloyd/roop-unleashed#516]
Traceback (most recent call last):
File "E:\Roop\roop-unleashed\installer_files\env\lib\site-packages\gradio\queueing.py", line 501, in call_prediction
output = await route_utils.call_process_api(
File "E:\Roop\roop-unleashed\installer_files\env\lib\site-packages\gradio\route_utils.py", line 253, in call_process_api
output = await app.get_blocks().process_api(
File "E:\Roop\roop-unleashed\installer_files\env\lib\site-packages\gradio\blocks.py", line 1695, in process_api
result = await self.call_function(
File "E:\Roop\roop-unleashed\installer_files\env\lib\site-packages\gradio\blocks.py", line 1247, in call_function
prediction = await utils.async_iteration(iterator)
File "E:\Roop\roop-unleashed\installer_files\env\lib\site-packages\gradio\utils.py", line 516, in async_iteration
return await iterator.anext()
File "E:\Roop\roop-unleashed\installer_files\env\lib\site-packages\gradio\utils.py", line 509, in anext
return await anyio.to_thread.run_sync(
File "E:\Roop\roop-unleashed\installer_files\env\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
return await get_async_backend().run_sync_in_worker_thread(
File "E:\Roop\roop-unleashed\installer_files\env\lib\site-packages\anyio_backends_asyncio.py", line 2144, in run_sync_in_worker_thread
return await future
File "E:\Roop\roop-unleashed\installer_files\env\lib\site-packages\anyio_backends_asyncio.py", line 851, in run
result = context.run(func, *args)
File "E:\Roop\roop-unleashed\installer_files\env\lib\site-packages\gradio\utils.py", line 492, in run_sync_iterator_async
return next(iterator)
File "E:\Roop\roop-unleashed\installer_files\env\lib\site-packages\gradio\utils.py", line 675, in gen_wrapper
response = next(iterator)
File "E:\Roop\roop-unleashed\roop-unleashed\ui\tabs\faceswap_tab.py", line 560, in start_swap
batch_process(list_files_process, use_clip, clip_text, processing_method == "In-Memory processing", imagemask, progress, SELECTED_INPUT_FACE_INDEX)
File "E:\Roop\roop-unleashed\roop-unleashed\roop\core.py", line 266, in batch_process
process_mgr.run_batch(origimages, fakeimages, roop.globals.execution_threads)
File "E:\Roop\roop-unleashed\roop-unleashed\roop\ProcessMgr.py", line 145, in run_batch
future.result()
File "E:\Roop\roop-unleashed\installer_files\env\lib\concurrent\futures_base.py", line 451, in result
return self.__get_result()
File "E:\Roop\roop-unleashed\installer_files\env\lib\concurrent\futures_base.py", line 403, in __get_result
raise self._exception
File "E:\Roop\roop-unleashed\installer_files\env\lib\concurrent\futures\thread.py", line 58, in run
result = self.fn(*self.args, self.kwargs)
File "E:\Roop\roop-unleashed\roop-unleashed\roop\ProcessMgr.py", line 155, in process_frames
resimg = self.process_frame(temp_frame)
File "E:\Roop\roop-unleashed\roop-unleashed\roop\ProcessMgr.py", line 300, in process_frame
num_swapped, temp_frame = self.swap_faces(frame, temp_frame)
File "E:\Roop\roop-unleashed\roop-unleashed\roop\ProcessMgr.py", line 332, in swap_faces
temp_frame = self.process_face(self.options.selected_index, face, temp_frame)
File "E:\Roop\roop-unleashed\roop-unleashed\roop\ProcessMgr.py", line 500, in process_face
fake_frame = p.Run(inputface, target_face, frame)
File "E:\Roop\roop-unleashed\roop-unleashed\roop\processors\FaceSwapInsightFace.py", line 27, in Run
img_fake, M = self.model_swap_insightface.get(temp_frame, target_face, source_face, paste_back=False)
File "E:\Roop\roop-unleashed\installer_files\env\lib\site-packages\insightface\model_zoo\inswapper.py", line 53, in get
pred = self.session.run(self.output_names, {self.input_names[0]: blob, self.input_names[1]: latent})[0]
File "E:\Roop\roop-unleashed\installer_files\env\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 220, in run
return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Conv node. Name:'Conv_42' Status Message: D:\a_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUDA failure 2: out of memory ; GPU=0 ; hostname=; file=D:\a_work\1\s\onnxruntime\core\providers\cuda\cuda_allocator.cc ; line=47 ; expr=cudaMalloc((void)&p, size);

What's wrong?

**Comment by lysxelapsed** [comment]
It already says what's wrong: `CUDA failure 2: out of memory ; GPU=0`
Either too many threads, or you're trying to run roop-unleashed on a GPU with too little VRAM. I always recommend a GPU with 6-8GB+. With 4GB you'll be able to run it, but not without issues.

**Comment by Ilay33** [comment]
I have 24GB of vram

**Comment by C0untFloyd** [comment]
> I have 24GB of vram

Prove it 😃

**Comment by Ilay33** [comment]
> > I have 24GB of vram
> 
> Prove it 😃

![image](https://github.com/C0untFloyd/roop-unleashed/assets/73934556/59e6df02-407b-47ad-971f-0b02687e2b1d)

**Comment by Ilay33** [comment]
> How many threads are you running? Do you have an additional on-board graphics card / Is GPU 0 (as shown in task manager) the one with 24GB VRAM? How's the VRAM usage when you start processing?

Gpu is 0
Idk about the other things

**Comment by C0untFloyd** [comment]
Still not convinced, looks like shared memory to me (onboard + nvidia). Anyway the number of threads can be adjusted in settings tab. I'd suggest starting with 2 first, also take a look into https://github.com/C0untFloyd/roop-unleashed/wiki/FAQ

**Comment by Ilay33** [comment]
> Still not convinced, looks like shared memory to me (onboard + nvidia). Anyway the number of threads can be adjusted in settings tab. I'd suggest starting with 2 first, also take a look into https://github.com/C0untFloyd/roop-unleashed/wiki/FAQ

I'm using 2

![image](https://github.com/C0untFloyd/roop-unleashed/assets/73934556/7e7699de-a548-40ef-85e6-70e09b09dbe9)
That's the shared one


![image](https://github.com/C0untFloyd/roop-unleashed/assets/73934556/969b2082-55e3-4828-a383-7f5163f352a5)

**Comment by Ilay33** [comment]
It's still not working
When I used v3.5.5 it worked fine

**Comment by lysxelapsed** [comment]
You can try lowering the threads in the settings tab. But if you don't need anything critical from 3.6.0, the easiest way would be to install [3.5.5](https://github.com/C0untFloyd/roop-unleashed/releases/tag/3.5.5) again.

**Comment by Bananacat89** [comment]
> You can try lowering the threads in the settings tab. But if you don't need anything critical from 3.6.0, the easiest way would be to install [3.5.5](https://github.com/C0untFloyd/roop-unleashed/releases/tag/3.5.5) again.

How do we install 3.5.5 again? I tried deleting the newest updated version and reinstalling the old one but it just auto installs the latest version. Do we need to change something in the startup scripts?

**Comment by lysxelapsed** [comment]
Shouldn't install the newest version unless you answer the update-question with yes. But not sure, since I'm not using the installer.
You can try a manual install and revert to 3.5.5, explained here: #210

**Comment by C0untFloyd** [comment]
Using the installer linked by @lysxelapsed should install v3.5.5. Just don't update when asked. Meanwhile 3.6.3 is released.

**Comment by Ilay33** [comment]
I've tried v3.6.3 and it didn't work too

**Comment by Ilay33** [comment]
Can you pls fix that problem?

**Comment by C0untFloyd** [comment]
I can't fix something when I don't know what's broken. It's working for me and lots of other people meaning it's something on your end, I'm pretty sure. Which cuda version did you install? You need CUDA Toolkit 11.8 and the same version CuDNN as described in the installation wiki.

**Comment by Ilay33** [comment]
But it worked with v3.5.5

**Comment by lysxelapsed** [comment]
> But it worked with v3.5.5

That doesn't guarantee, that your current issues are related to the update. My best guess is still, that roop-unleashed with your other apps combined (even windows explorer takes up VRAM, for every single window) simply goes over your available amount. Because the error message is very clear, that you're out of GPU memory. Try restarting your system and/or a lower thread count in the settings.
I compared the VRAM usage in 3.5.5, 3.6.0 and 3.6.3 and don't see any real difference.

**Comment by Ilay33** [comment]
So why v3.5.5 worked and v3.6.0 & v3.6.3 don't work?

**Comment by Ilay33** [comment]
I have 24GB of VRAM

**Comment by C0untFloyd** [comment]
I'm sorry, but this is pointless. Either go back and install the older version or try analyzing whatever changed in your environment.
