### ISSUE TITLE
AMD cuda error

### ISSUE THREAD

**Issue by turkiet** [C0untFloyd/roop-unleashed#688]
`FFmpeg is already installed.
Skipping FFmpeg installation as it is already available.
Launching roop unleashed
Check for Updates? [y/n]n
Launching App
Using provider ['CUDAExecutionProvider'] - Device:cuda

Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
download_path: E:\yapay-zeka\roop-unleashed\roop-unleashed\models\buffalo_l
Downloading E:\yapay-zeka\roop-unleashed\roop-unleashed\models\buffalo_l.zip from https://github.com/deepinsight/insightface/releases/download/v0.7/buffalo_l.zip...
100%|███████████████████████████████████████████████████████████████████████| 281857/281857 [00:13<00:00, 21374.96KB/s]
*************** EP Error ***************
EP Error D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUDA failure 35: CUDA driver version is insufficient for CUDA runtime version ; GPU=261996208 ; hostname=DOGUKAN ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_execution_provider.cc ; line=245 ; expr=cudaSetDevice(info_.device_id);

 when using ['CUDAExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
****************************************
*************** EP Error ***************
EP Error D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUDA failure 35: CUDA driver version is insufficient for CUDA runtime version ; GPU=264029904 ; hostname=DOGUKAN ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_execution_provider.cc ; line=245 ; expr=cudaSetDevice(info_.device_id);

 when using ['CUDAExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
****************************************
Traceback (most recent call last):
  File "E:\yapay-zeka\roop-unleashed\installer_files\env\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "E:\yapay-zeka\roop-unleashed\installer_files\env\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 483, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
RuntimeError: D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUDA failure 35: CUDA driver version is insufficient for CUDA runtime version ; GPU=264029904 ; hostname=DOGUKAN ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_execution_provider.cc ; line=245 ; expr=cudaSetDevice(info_.device_id);

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\yapay-zeka\roop-unleashed\installer_files\env\lib\site-packages\gradio\queueing.py", line 566, in process_events
    response = await route_utils.call_process_api(
  File "E:\yapay-zeka\roop-unleashed\installer_files\env\lib\site-packages\gradio\route_utils.py", line 270, in call_process_api
    output = await app.get_blocks().process_api(
  File "E:\yapay-zeka\roop-unleashed\installer_files\env\lib\site-packages\gradio\blocks.py", line 1847, in process_api
    result = await self.call_function(
  File "E:\yapay-zeka\roop-unleashed\installer_files\env\lib\site-packages\gradio\blocks.py", line 1445, in call_function
    prediction = await utils.async_iteration(iterator)
  File "E:\yapay-zeka\roop-unleashed\installer_files\env\lib\site-packages\gradio\utils.py", line 629, in async_iteration
    return await iterator.__anext__()
  File "E:\yapay-zeka\roop-unleashed\installer_files\env\lib\site-packages\gradio\utils.py", line 622, in __anext__
    return await anyio.to_thread.run_sync(
  File "E:\yapay-zeka\roop-unleashed\installer_files\env\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "E:\yapay-zeka\roop-unleashed\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "E:\yapay-zeka\roop-unleashed\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "E:\yapay-zeka\roop-unleashed\installer_files\env\lib\site-packages\gradio\utils.py", line 605, in run_sync_iterator_async
    return next(iterator)
  File "E:\yapay-zeka\roop-unleashed\installer_files\env\lib\site-packages\gradio\utils.py", line 788, in gen_wrapper
    response = next(iterator)
  File "E:\yapay-zeka\roop-unleashed\roop-unleashed\ui\tabs\faceswap_tab.py", line 621, in start_swap
    batch_process_regular(list_files_process, mask_engine, clip_text, processing_method == "In-Memory processing", imagemask, num_swap_steps, progress, SELECTED_INPUT_FACE_INDEX)
  File "E:\yapay-zeka\roop-unleashed\roop-unleashed\roop\core.py", line 218, in batch_process_regular
    process_mgr.initialize(roop.globals.INPUT_FACESETS, roop.globals.TARGET_FACES, options)
  File "E:\yapay-zeka\roop-unleashed\roop-unleashed\roop\ProcessMgr.py", line 126, in initialize
    p.Initialize(extoption)
  File "E:\yapay-zeka\roop-unleashed\roop-unleashed\roop\processors\FaceSwapInsightFace.py", line 36, in Initialize
    self.model_swap_insightface = onnxruntime.InferenceSession(model_path, sess_options, providers=roop.globals.execution_providers)
  File "E:\yapay-zeka\roop-unleashed\installer_files\env\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 432, in __init__
    raise fallback_error from e
  File "E:\yapay-zeka\roop-unleashed\installer_files\env\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 427, in __init__
    self._create_inference_session(self._fallback_providers, None)
  File "E:\yapay-zeka\roop-unleashed\installer_files\env\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 483, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
RuntimeError: D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUDA failure 35: CUDA driver version is insufficient for CUDA runtime version ; GPU=264029904 ; hostname=DOGUKAN ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_execution_provider.cc ; line=245 ; expr=cudaSetDevice(info_.device_id);`

My gpu is AMD.
my OS is Windows 10

https://github.com/C0untFloyd/roop-unleashed/wiki/Installation
I did what it says here for AMD.
I get this error when I add a face and press "start" (both times it gives me an error)
![hata](https://github.com/C0untFloyd/roop-unleashed/assets/54305695/507a0a1f-ae3e-438c-8103-08540fbc6c7b)

**Comment by lysxelapsed** [comment]
Cuda is for Nvidia cards, directml for AMD cards (which one?). If everything is installed properly, directml should show up as provider in the settings tab. Select that, apply settings and restart roop-unleashed.

**Comment by turkiet** [comment]
> Cuda is for Nvidia cards, directml for AMD cards (which one?). If everything is installed properly, directml should show up as provider in the settings tab. Select that, apply settings and restart roop-unleashed.

directml is not visible.

**Comment by turkiet** [comment]
I fixed it.

I made sure to specify the path for anaconda beforehand.
https://eduand-alvarez.medium.com/setting-up-anaconda-on-your-windows-pc-6e39800c1afb

[https://github.com/C0untFloyd/roop-unleashed/issues/625#issuecomment-2072361976](url)

Then I opened CMD and started it by saying "start windows_run.bat". When the browser opened, I exited by saying "Y" with the ctrl+c combination and it gave me write permission. I entered the command "pip install onnxruntime-directml" and it fixed it. And so "dml" appears in the settings.
