### ISSUE TITLE
cud error 

### ISSUE THREAD

**Issue by zachysaur** [C0untFloyd/roop-unleashed#806]
Roop-Unleashed 4.1\roop-unleashed-main\venv\lib\site-packages\gradio\components\dropdown.py:187: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include: cuda or set allow_custom_value=True.
  warnings.warn(
Running on local URL:  http://127.0.0.1:7860
INFO:httpx:HTTP Request: GET http://127.0.0.1:7860/startup-events "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD http://127.0.0.1:7860/ "HTTP/1.1 200 OK"

To create a public link, set `share=True` in `launch()`.

**Comment by KalliasX** [comment]
Yeah I have a CUDA error too... what I find strange is the path to a D: drive, my computer has none. Maybe there is a hardcoded path in the code?

EP Error D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall

**Comment by zachysaur** [comment]
i solved it by uninstalling onnixruntime 1.17 and installing 1.15

**Comment by KalliasX** [comment]
Hi Zach, would you mind providing the commands to do that, please? Thx in advance

**Comment by nitinmukesh** [comment]
> Hi Zach, would you mind providing the commands to do that, please? Thx in advance

pip install onnxruntime==1.15.1

**Comment by DarthKX** [comment]
thx, does that uninstall 1.17?

**Comment by zachysaur** [comment]
yes

**Comment by C0untFloyd** [comment]
https://github.com/C0untFloyd/roop-unleashed/wiki/FAQ#when-starting-a-face-swap-or-preview-this-error-shows-up-excerpt-cuda-failure-35-cuda-driver-version-is-insufficient-for-cuda-runtime-version

**Comment by ctxadm** [comment]
fixed by:

-> pip uninstall onnxruntime onnxruntime-gpu 

-> pip install onnxruntime-gpu==1.15.1
