### ISSUE TITLE
Issues -> Discussions

### ISSUE THREAD

**Issue by forgiga** [C0untFloyd/roop-unleashed#848]
Hello guys, I hope you are doing great.

I'm a new and absolutely inexperienced user here. I just learned about Roop Unleashed from a YouTube video. I downloaded a ZIP folder and installed Visual Studio. After installing Visual Studio and selecting the necessary components (Desktop C++ and Gaming C++—as recommended by the YouTube video), I restarted my PC. After that, I unzipped the roop-unleashed-main.zip file and ran the installer. Once the installation was complete, Roop automatically opened in the web browser (Chrome). Since I do not have a dedicated video card, I selected CPU in the settings. Up to that point, everything seemed fine. I uploaded a photo of the face as the Source and a video as the Target, then tried to select "Use face from this frame," but encountered a "No faces found" error.

Despite this, I pressed the Start button, and this error message appeared:
error
[ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUBLAS failure 3: CUBLAS_STATUS_ALLOC_FAILED ; GPU=0 ; hostname=DESKTOP-QLKDDEC ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_execution_provider.cc ; line=173 ; expr=cublasCreate(&cublas_handle_);

Followed by this warning:
warning
ffmpeg is not installed! No video processing possible.

 I decided to close the browser tab and tried to run the file again. Among the many other lines in the command prompt I noticed this message:
To use videos, you need to restart roop after this installation.

Which I did. But it didn't help

I successfully installed the ffmpeg manually and restarted the application again. But the error is still there.

What did I do wrong or what should I do else? 
Thank you.

**Comment by SakoJutin** [comment]
First of all you have to install Nvidia Cuda
Then you have to put your ffmpeg app in C drive and add to system environment

**Comment by SakoJutin** [comment]
> First of all you have to install Nvidia Cuda Then you have to put your ffmpeg app in C drive and add to system environment

**See the trick here** 
https://phoenixnap.com/kb/ffmpeg-windows

**Comment by forgiga** [comment]
Thank you! 
You helped me a lot!
Nvidia Cuda was a missing component. 
All works now

**Comment by SakoJutin** [comment]
> Thank you! You helped me a lot! But the issues are still here. Nvidia Cuda was a missing component. After installing Cuda the Roop application successfully worked once (one time only). It recognized the faces, processed the video and showed the final result file. But at the next launch, all the errors appeared again.

Drop as screen shot please

**Comment by Axlrachel2024** [comment]
dude i have the same issue man im new to all this lot and can not for the life of me figure it out man its really p1ss1ng me off now lol any chance one you guys can jump on to anydesk on my pc and sort it out for me please c0untfloyd maybe you as your the creator if you have spare time that is im really struggling man i had the same thing with streamwall trying to get that to work to can anyone help me please thanks
